// Code generated by pricing/gen from v2026.09.04-3b4770f (3b4770fcb45f5f76658893ae7faa0bc7b11d092c); DO NOT EDIT.

package pricing

import "time"

const generatedTag = "v2026.09.04-3b4770f"
const generatedIndexCommit = "3b4770fcb45f5f76658893ae7faa0bc7b11d092c"
const generatedDataModified = "2026-09-04"

// modelSeries maps a canonical anthropic model id to its
// point-in-time input/output price history (half-open [from,to)),
// plus the recorded cache-read series where the dataset publishes one.
var modelSeries = map[string]modelHist{
	"claude-3-5-haiku-20241022": {
		input: []priceInterval{
			{from: time.Date(2024, 11, 4, 0, 0, 0, 0, time.UTC), to: ptrTime(time.Date(2024, 12, 3, 0, 0, 0, 0, time.UTC)), priceUSD: 1.0},
			{from: time.Date(2024, 12, 3, 0, 0, 0, 0, time.UTC), to: ptrTime(time.Date(2026, 2, 19, 0, 0, 0, 0, time.UTC)), priceUSD: 0.8},
		},
		output: []priceInterval{
			{from: time.Date(2024, 11, 4, 0, 0, 0, 0, time.UTC), to: ptrTime(time.Date(2024, 12, 3, 0, 0, 0, 0, time.UTC)), priceUSD: 5.0},
			{from: time.Date(2024, 12, 3, 0, 0, 0, 0, time.UTC), to: ptrTime(time.Date(2026, 2, 19, 0, 0, 0, 0, time.UTC)), priceUSD: 4.0},
		},
	},
	"claude-3-5-sonnet-20240620": {
		input: []priceInterval{
			{from: time.Date(2024, 6, 20, 0, 0, 0, 0, time.UTC), to: ptrTime(time.Date(2025, 10, 28, 0, 0, 0, 0, time.UTC)), priceUSD: 3.0},
		},
		output: []priceInterval{
			{from: time.Date(2024, 6, 20, 0, 0, 0, 0, time.UTC), to: ptrTime(time.Date(2025, 10, 28, 0, 0, 0, 0, time.UTC)), priceUSD: 15.0},
		},
	},
	"claude-3-7-sonnet-20250219": {
		input: []priceInterval{
			{from: time.Date(2025, 2, 24, 0, 0, 0, 0, time.UTC), to: ptrTime(time.Date(2026, 2, 19, 0, 0, 0, 0, time.UTC)), priceUSD: 3.0},
		},
		output: []priceInterval{
			{from: time.Date(2025, 2, 24, 0, 0, 0, 0, time.UTC), to: ptrTime(time.Date(2026, 2, 19, 0, 0, 0, 0, time.UTC)), priceUSD: 15.0},
		},
	},
	"claude-3-haiku-20240307": {
		input: []priceInterval{
			{from: time.Date(2024, 3, 4, 0, 0, 0, 0, time.UTC), to: ptrTime(time.Date(2026, 4, 20, 0, 0, 0, 0, time.UTC)), priceUSD: 0.25},
		},
		output: []priceInterval{
			{from: time.Date(2024, 3, 4, 0, 0, 0, 0, time.UTC), to: ptrTime(time.Date(2026, 4, 20, 0, 0, 0, 0, time.UTC)), priceUSD: 1.25},
		},
	},
	"claude-3-opus-20240229": {
		input: []priceInterval{
			{from: time.Date(2024, 3, 4, 0, 0, 0, 0, time.UTC), to: ptrTime(time.Date(2026, 1, 5, 0, 0, 0, 0, time.UTC)), priceUSD: 15.0},
		},
		output: []priceInterval{
			{from: time.Date(2024, 3, 4, 0, 0, 0, 0, time.UTC), to: ptrTime(time.Date(2026, 1, 5, 0, 0, 0, 0, time.UTC)), priceUSD: 75.0},
		},
	},
	"claude-3-sonnet-20240229": {
		input: []priceInterval{
			{from: time.Date(2024, 3, 4, 0, 0, 0, 0, time.UTC), to: ptrTime(time.Date(2025, 7, 21, 0, 0, 0, 0, time.UTC)), priceUSD: 3.0},
		},
		output: []priceInterval{
			{from: time.Date(2024, 3, 4, 0, 0, 0, 0, time.UTC), to: ptrTime(time.Date(2025, 7, 21, 0, 0, 0, 0, time.UTC)), priceUSD: 15.0},
		},
	},
	"claude-fable-5": {
		input: []priceInterval{
			{from: time.Date(2026, 6, 9, 0, 0, 0, 0, time.UTC), to: nil, priceUSD: 10.0},
		},
		output: []priceInterval{
			{from: time.Date(2026, 6, 9, 0, 0, 0, 0, time.UTC), to: nil, priceUSD: 50.0},
		},
		cacheRead: []priceInterval{
			{from: time.Date(2026, 7, 31, 0, 0, 0, 0, time.UTC), to: nil, priceUSD: 1.0},
		},
	},
	"claude-fable-5-1": {
		input: []priceInterval{
			{from: time.Date(2026, 9, 2, 0, 0, 0, 0, time.UTC), to: nil, priceUSD: 10.0},
		},
		output: []priceInterval{
			{from: time.Date(2026, 9, 2, 0, 0, 0, 0, time.UTC), to: nil, priceUSD: 50.0},
		},
		cacheRead: []priceInterval{
			{from: time.Date(2026, 9, 2, 0, 0, 0, 0, time.UTC), to: nil, priceUSD: 0.25},
		},
	},
	"claude-haiku-4-5-20251001": {
		input: []priceInterval{
			{from: time.Date(2025, 10, 15, 0, 0, 0, 0, time.UTC), to: nil, priceUSD: 1.0},
		},
		output: []priceInterval{
			{from: time.Date(2025, 10, 15, 0, 0, 0, 0, time.UTC), to: nil, priceUSD: 5.0},
		},
		cacheRead: []priceInterval{
			{from: time.Date(2026, 7, 31, 0, 0, 0, 0, time.UTC), to: nil, priceUSD: 0.1},
		},
	},
	"claude-mythos-5": {
		input: []priceInterval{
			{from: time.Date(2026, 6, 22, 0, 0, 0, 0, time.UTC), to: ptrTime(time.Date(2026, 6, 29, 0, 0, 0, 0, time.UTC)), priceUSD: 10.0},
			{from: time.Date(2026, 6, 29, 0, 0, 0, 0, time.UTC), to: nil, priceUSD: 10.0},
		},
		output: []priceInterval{
			{from: time.Date(2026, 6, 22, 0, 0, 0, 0, time.UTC), to: ptrTime(time.Date(2026, 6, 29, 0, 0, 0, 0, time.UTC)), priceUSD: 50.0},
			{from: time.Date(2026, 6, 29, 0, 0, 0, 0, time.UTC), to: nil, priceUSD: 50.0},
		},
		cacheRead: []priceInterval{
			{from: time.Date(2026, 6, 22, 0, 0, 0, 0, time.UTC), to: ptrTime(time.Date(2026, 6, 29, 0, 0, 0, 0, time.UTC)), priceUSD: 1.0},
			{from: time.Date(2026, 6, 29, 0, 0, 0, 0, time.UTC), to: nil, priceUSD: 1.0},
		},
	},
	"claude-mythos-5-1": {
		input: []priceInterval{
			{from: time.Date(2026, 9, 2, 0, 0, 0, 0, time.UTC), to: nil, priceUSD: 10.0},
		},
		output: []priceInterval{
			{from: time.Date(2026, 9, 2, 0, 0, 0, 0, time.UTC), to: nil, priceUSD: 50.0},
		},
		cacheRead: []priceInterval{
			{from: time.Date(2026, 9, 2, 0, 0, 0, 0, time.UTC), to: nil, priceUSD: 0.25},
		},
	},
	"claude-opus-4-1-20250805": {
		input: []priceInterval{
			{from: time.Date(2025, 8, 5, 0, 0, 0, 0, time.UTC), to: nil, priceUSD: 15.0},
		},
		output: []priceInterval{
			{from: time.Date(2025, 8, 5, 0, 0, 0, 0, time.UTC), to: nil, priceUSD: 75.0},
		},
		cacheRead: []priceInterval{
			{from: time.Date(2026, 7, 31, 0, 0, 0, 0, time.UTC), to: nil, priceUSD: 1.5},
		},
	},
	"claude-opus-4-20250514": {
		input: []priceInterval{
			{from: time.Date(2025, 5, 14, 0, 0, 0, 0, time.UTC), to: nil, priceUSD: 15.0},
		},
		output: []priceInterval{
			{from: time.Date(2025, 5, 14, 0, 0, 0, 0, time.UTC), to: nil, priceUSD: 75.0},
		},
		cacheRead: []priceInterval{
			{from: time.Date(2026, 7, 31, 0, 0, 0, 0, time.UTC), to: nil, priceUSD: 1.5},
		},
	},
	"claude-opus-4-5-20251101": {
		input: []priceInterval{
			{from: time.Date(2025, 11, 1, 0, 0, 0, 0, time.UTC), to: nil, priceUSD: 5.0},
		},
		output: []priceInterval{
			{from: time.Date(2025, 11, 1, 0, 0, 0, 0, time.UTC), to: nil, priceUSD: 25.0},
		},
		cacheRead: []priceInterval{
			{from: time.Date(2026, 7, 31, 0, 0, 0, 0, time.UTC), to: nil, priceUSD: 0.5},
		},
	},
	"claude-opus-4-6": {
		input: []priceInterval{
			{from: time.Date(2026, 2, 5, 0, 0, 0, 0, time.UTC), to: nil, priceUSD: 5.0},
		},
		output: []priceInterval{
			{from: time.Date(2026, 2, 5, 0, 0, 0, 0, time.UTC), to: nil, priceUSD: 25.0},
		},
		cacheRead: []priceInterval{
			{from: time.Date(2026, 7, 31, 0, 0, 0, 0, time.UTC), to: nil, priceUSD: 0.5},
		},
	},
	"claude-opus-4-7": {
		input: []priceInterval{
			{from: time.Date(2026, 4, 16, 0, 0, 0, 0, time.UTC), to: nil, priceUSD: 5.0},
		},
		output: []priceInterval{
			{from: time.Date(2026, 4, 16, 0, 0, 0, 0, time.UTC), to: nil, priceUSD: 25.0},
		},
		cacheRead: []priceInterval{
			{from: time.Date(2026, 7, 31, 0, 0, 0, 0, time.UTC), to: nil, priceUSD: 0.5},
		},
	},
	"claude-opus-4-8": {
		input: []priceInterval{
			{from: time.Date(2026, 5, 28, 0, 0, 0, 0, time.UTC), to: nil, priceUSD: 5.0},
		},
		output: []priceInterval{
			{from: time.Date(2026, 5, 28, 0, 0, 0, 0, time.UTC), to: nil, priceUSD: 25.0},
		},
		cacheRead: []priceInterval{
			{from: time.Date(2026, 7, 31, 0, 0, 0, 0, time.UTC), to: nil, priceUSD: 0.5},
		},
	},
	"claude-opus-5": {
		input: []priceInterval{
			{from: time.Date(2026, 7, 24, 0, 0, 0, 0, time.UTC), to: nil, priceUSD: 5.0},
		},
		output: []priceInterval{
			{from: time.Date(2026, 7, 24, 0, 0, 0, 0, time.UTC), to: nil, priceUSD: 25.0},
		},
		cacheRead: []priceInterval{
			{from: time.Date(2026, 7, 24, 0, 0, 0, 0, time.UTC), to: nil, priceUSD: 0.5},
		},
	},
	"claude-sonnet-4-20250514": {
		input: []priceInterval{
			{from: time.Date(2025, 5, 14, 0, 0, 0, 0, time.UTC), to: nil, priceUSD: 3.0},
		},
		output: []priceInterval{
			{from: time.Date(2025, 5, 14, 0, 0, 0, 0, time.UTC), to: nil, priceUSD: 15.0},
		},
		cacheRead: []priceInterval{
			{from: time.Date(2026, 7, 31, 0, 0, 0, 0, time.UTC), to: nil, priceUSD: 0.3},
		},
	},
	"claude-sonnet-4-5-20250929": {
		input: []priceInterval{
			{from: time.Date(2025, 9, 29, 0, 0, 0, 0, time.UTC), to: nil, priceUSD: 3.0},
		},
		output: []priceInterval{
			{from: time.Date(2025, 9, 29, 0, 0, 0, 0, time.UTC), to: nil, priceUSD: 15.0},
		},
		cacheRead: []priceInterval{
			{from: time.Date(2026, 7, 31, 0, 0, 0, 0, time.UTC), to: nil, priceUSD: 0.3},
		},
	},
	"claude-sonnet-4-6": {
		input: []priceInterval{
			{from: time.Date(2026, 2, 17, 0, 0, 0, 0, time.UTC), to: nil, priceUSD: 3.0},
		},
		output: []priceInterval{
			{from: time.Date(2026, 2, 17, 0, 0, 0, 0, time.UTC), to: nil, priceUSD: 15.0},
		},
		cacheRead: []priceInterval{
			{from: time.Date(2026, 7, 31, 0, 0, 0, 0, time.UTC), to: nil, priceUSD: 0.3},
		},
	},
	"claude-sonnet-5": {
		input: []priceInterval{
			{from: time.Date(2026, 7, 1, 0, 0, 0, 0, time.UTC), to: nil, priceUSD: 2.0},
		},
		output: []priceInterval{
			{from: time.Date(2026, 7, 1, 0, 0, 0, 0, time.UTC), to: nil, priceUSD: 10.0},
		},
		cacheRead: []priceInterval{
			{from: time.Date(2026, 7, 1, 0, 0, 0, 0, time.UTC), to: nil, priceUSD: 0.2},
		},
	},
}

// modelAliases maps an alias (short or display form) to the
// canonical model id in modelSeries.
var modelAliases = map[string]string{
	"claude-haiku-4-5":  "claude-haiku-4-5-20251001",
	"claude-opus-4-1":   "claude-opus-4-1-20250805",
	"claude-opus-4-5":   "claude-opus-4-5-20251101",
	"claude-sonnet-4-5": "claude-sonnet-4-5-20250929",
}
